---
title: "COVID-19 NYT DATA EDA"
output: html_document
---

# Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(tidymodels)
library(dplyr)
library(plotly)
library(RCurl)
library(maps)
```

# Load Data
```{r}
# Read COVID data from URL links
# Counties
county.link = getURL("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv")
counties = read.csv(text = county.link)
# States
state.link = getURL("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv")
states = read.csv(text = state.link)

# US Population data
pop = read.csv("~/Github/COVID/COVID_Shiny/coviz/nst-est2019-alldata.csv")

# Shelter In Place data
sip = read.csv("~/Github/COVID/COVID_Shiny/coviz/sip.csv")

sip = sip %>% select(state, order_date)

pop = pop %>%
    select(NAME, POPESTIMATE2019)

# List of "states" not to include
remove_states = c("American Samoa", "Guam", "Northern Mariana Islands", "Virgin Islands")

# Filter out
states = states %>% filter(!(state %in% remove_states))

# Reassign date values
counties$date = lubridate::ymd(counties$date)
states$date = lubridate::ymd(states$date)

# Growth Rate var
counties = counties %>%
    group_by(state, county, fips, date) %>%
    arrange(date) %>%
    summarise(
        cases = sum(cases),
        deaths = sum(deaths),
        death_rate = round((deaths / cases)*100, 2)
    )

states = states %>%
    group_by(state, fips, date) %>%
    arrange(date) %>%
    summarise(
        cases = sum(cases),
        deaths = sum(deaths),
        death_rate = round((deaths / cases)*100, 2)
    ) %>%
    left_join(sip, by = c("state")) %>%
    mutate(
        order_date = lubridate::ymd(order_date)
    )
```

# Plot Growth of States
```{r}
ggplot(states, aes(date, cases, colour = state)) +
    geom_point() + 
    geom_line() -> statePlot

ggplotly(statePlot)
```

# Subset to Minnesota
```{r}
mn <- counties %>% filter(state == 'Minnesota')
mn <- mn %>%
    mutate(
        deathRate = deaths / cases
    )
```

# Plot County Growth
```{r}
ggplot(mn, aes(date, deathRate, colour = county)) +
    geom_point() +
    geom_line() -> mnCounties

ggplotly(mnCounties)
```

# Plot Map of MN
```{r}
library(urbnmapr)
```

```{r}
mn <- mn %>% ungroup()
mn <- mn %>% mutate(fips = as.character(fips))
mn_county <- mn %>% left_join(urbnmapr::counties, by = c("fips" = "county_fips"))
```

```{r}
mn_county %>%
  ggplot(aes(long, lat, group = group, fill = cases)) +
  geom_polygon(color = NA) +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  labs(fill = "Cases by County")
```

# Feature Engineering
```{r}
# Calculate days to 100, 500, 1000 and 5000 cases
states <- states %>%
    mutate(
        daysTo100 = case_when(
            cases < 100 ~ 1,
            T ~ 0
        ),
        daysTo500 = case_when(
            cases < 500 ~ 1,
            T ~ 0
        ),
        daysTo1000 = case_when(
            cases < 1000 ~ 1,
            T ~ 0
        ),
        daysTo5000 = case_when(
            cases < 5000 ~ 1,
            T ~ 0
        )
    )
```

```{r}
# Group data by state
state_group <- states %>%
    group_by(state) %>%
    summarise(
        daysUnder100 = sum(daysTo100),
        daysUnder500 = sum(daysTo500),
        daysUnder1000 = sum(daysTo1000),
        daysUnder5000 = sum(daysTo5000)
    )
```

## Plot Days To Data
```{r}
# Days to 100
ggplot(state_group, aes(reorder(state, -daysUnder100), daysUnder100, fill = state)) +
    geom_bar(stat = "identity") +
    theme(legend.position="none") +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    ggtitle("Days Under 100 Cases") +
    labs(x = "State", y = "Days")
# Days to 500
ggplot(state_group, aes(reorder(state, -daysUnder500), daysUnder500, fill = state)) +
    geom_bar(stat = "identity") +
    theme(legend.position="none") +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    ggtitle("Days Under 500 Cases") +
    labs(x = "State", y = "Days")
# Days to 1000
ggplot(state_group, aes(reorder(state, -daysUnder1000), daysUnder1000, fill = state)) +
    geom_bar(stat = "identity") +
    theme(legend.position="none") +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    ggtitle("Days Under 100 Cases") +
    labs(x = "State", y = "Days")
# Days to 5000
ggplot(state_group, aes(reorder(state, -daysUnder5000), daysUnder5000, fill = state)) +
    geom_bar(stat = "identity") +
    theme(legend.position="none") +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    ggtitle("Days Under 5000 Cases") +
    labs(x = "State", y = "Days")
```














